### ISSUE TITLE
Maintain a happy and effective Fellowship team

### ISSUE THREAD

**Issue by laulowen** [openfoodfacts/offf#1]
### Who for
This is for everyone contributing to the Google Fellowship, and more specifically to the full time team.

### What
A grouping of activities and documents to organise ourselves, stay connected, improve our way of working together, and anything else to make the Fellowship team an awesome one.

- [ ] Define and maintain a team-wide backlog tracker of work items
- [ ] Run a team retro at least once per month
- [ ] Create & automate deployment to dev environment for Product Opener / Robotoff / Flutter app
- [ ] Automate releases of Product Opener / Robotoff / Flutter app
- [ ] Improve and unify monitoring, logging and tracing
- [ ] Accelerate development velocity for Robotoff, Product Opener, Flutter app
- [ ] Run at least two team building activities
- [ ] A Handoff Guide for each workstream by Fellowship completion

### Why
Effective teams don't just happen - it takes intentional work to develop this effectiveness. This is especially true when the team is big, brand new and distributed.

### Part of
- https://github.com/openfoodfacts/offf/issues/20
