### ISSUE TITLE
Geographical Scale (with disclaimers)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/offf#13]
Expand the Geographical Scale of Environmental scoring (with disclaimers)

- [ ] Approved plan to display an environmental score in all countries in the world
- [ ] Implement an environmental score in all countries on app and website
  - [ ] Add a disclaimer API
- [ ] Determine the feasibility of improving the accuracy of Eco Score in new countries 
- [ ] Compute geographically expanded Eco-Score in n countries including improving ingredients analysis in new languages
