### ISSUE TITLE
Score Accuracy & Comparison - As an OFF user I want products in the same category to differ so that I can choose the best product

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/offf#14]
### Who for
- As an OFF user I want products in the same category to differ so that I can choose the best product
- As a Producer, I want ways to improve my products
- A a consumer, I want to make better choices within a category

### What
- [ ] Map Agribalyse LCAs to Open Food Facts ingredients
  - [ ] https://github.com/openfoodfacts/openfoodfacts-server/pull/5454
- [ ] Approved plan to calculate unique Eco-Scores within the same category
- [ ] Launch an async task that computes refined Eco-Scores based on Product Opener ingredients for X many products.
  - [x] #5 
  - [x] #6 
  - [ ]  #7
- [ ] At least X% of Product Opener products have an ingredient based refined Eco-Score.
- [ ] Rollout unique Eco-Scores to app and web
  - [ ] #8 
  - [ ] #9
### Part of
- #12 

### Why
As an OFF user I want products in the same category to differ so that I can choose the best product
