### ISSUE TITLE
ML Detection

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/offf#15]
### What

- [ ] Improve automatic category detection by X% 
https://github.com/openfoodfacts/robotoff/issues/369
- [ ] Enable model retraining on validated detections
https://github.com/openfoodfacts/robotoff/issues/370
- [ ] Improve performance of ML label/pictogram detection
https://github.com/openfoodfacts/robotoff/issues/371

### Part of
- #12
