### ISSUE TITLE
Geographical Scale (with disclaimers) - As an OFF user I want to see Eco-Score outside of France so that I can choose the best product

### ISSUE THREAD

**Issue by zond** [openfoodfacts/offf#4]
### Who for
- Users

### What
Expand the Geographical Scale of Environmental scoring (with disclaimers)

- [ ] Approved plan to display an environmental score in all countries in the world
- [ ] Implement an environmental score in all countries on app and website
  - [ ] Add a disclaimer API
- [ ] Determine the feasibility of improving the accuracy of Eco Score in new countries 
- [ ] Compute geographically expanded Eco-Score in n countries including improving ingredients analysis in new languages
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/5503

### Part of
- #12
